doc/shopfloor_api.rst: Fix incorrect shopfloor service module name
The `make doc` pre-submit hook is complaining `AttributeError: module
'shopfloor_service' has no attribute 'ShopfloorService'`. This is
because the module name is wrong.

BUG=None
TEST=make doc
TEST=make test

Change-Id: Ie7103cb30380ed296d0104705c78906720b379b7
Reviewed-on: https://chromium-review.googlesource.com/c/chromiumos/platform/factory/+/5825377
Auto-Submit: Wen-Ting Tseng <wdzeng@chromium.org>
Commit-Queue: Wen-Ting Tseng <wdzeng@chromium.org>
Tested-by: Wen-Ting Tseng <wdzeng@chromium.org>
Reviewed-by: Phoebe Wang <phoebewang@chromium.org>